In [1]:
from bs4 import BeautifulSoup
import requests

url = "http://www.mfd.gov.np/"
response = requests.get(url)

soup = BeautifulSoup(response.content, "html.parser")

In [2]:
right_table=soup.find('table', class_='table')

In [3]:
right_table

<table class="table" style="margin-bottom: 0px"><tr><th>Station</th><th class="center">Maximum Temp.<br/>(°C)</th><th class="center">Minimum Temp.<br/>(°C)</th><th class="center">24 hrs Rainfall<br/>(mm)</th></tr><tr><td>Dipayal</td><td class="center">34.0</td><td class="center">15.8</td><td class="center">0.0</td></tr><tr><td>Dadeldhura</td><td class="center">24.8</td><td class="center">11.3</td><td class="center">0.0</td></tr><tr><td>Dhangadi</td><td class="center">34.5</td><td class="center">20.2</td><td class="center">0.0</td></tr><tr><td>Birendranagar</td><td class="center">31.5</td><td class="center">16.5</td><td class="center">0.0</td></tr><tr><td>Nepalgunj</td><td class="center">34.2</td><td class="center">21.4</td><td class="center">0.0</td></tr><tr><td>Jumla</td><td class="center">23.6</td><td class="center">11.5</td><td class="center">0.0</td></tr><tr><td>Dang</td><td class="center">33.0</td><td class="center">17.0</td><td class="center">0.0</td></tr><tr><td>Pokhara</td><td class="center">31.2</td><td class="center">18.5</td><td class="center">0.0</td></tr><tr><td>Bhairahawa</td><td class="center">36.4</td><td class="center">21.6</td><td class="center">0.0</td></tr><tr><td>Simara</td><td class="center">35.4</td><td class="center">20.0</td><td class="center">0.0</td></tr><tr><td>Kathmandu</td><td class="center">30.5</td><td class="center">14.4</td><td class="center">0.0</td></tr><tr><td>Okhaldhunga</td><td class="center">27.2</td><td class="center">16.6</td><td class="center">0.0</td></tr><tr><td>Taplejung</td><td class="center">27.0</td><td class="center">13.8</td><td class="center">0.0</td></tr><tr><td>Dhankuta</td><td class="center">29.6</td><td class="center">16.4</td><td class="center">0.0</td></tr><tr><td>Biratnagar</td><td class="center">34.0</td><td class="center">22.0</td><td class="center">0.0</td></tr><tr><td>Jomsom</td><td class="center">19.0</td><td class="center">8.5</td><td class="center">0.0*</td></tr><tr><td>Lumle</td><td class="center">24.5</td><td class="center">14.5</td><td class="center">0.0*</td></tr><tr><td>Jankapur</td><td class="center">34.2</td><td class="center">23.8</td><td class="center">0.0*</td></tr><tr><td>Jiri</td><td class="center">26.0</td><td class="center">9.5</td><td class="center">0.0*</td></tr><tr><td align="right" colspan="4"><small>* Daily rainfall data ending at 08:45 AM NPT</small></td></tr></table>

In [4]:
import pandas as pd

In [5]:
#Generate lists
A=[]
B=[]
C=[]
D=[]

for row in right_table.findAll("tr"):
    cells = row.findAll('td')
    if len(cells)==4:
        A.append(cells[0].find(text=True))
        B.append(cells[1].find(text=True))
        C.append(cells[2].find(text=True))
        D.append(cells[3].find(text=True))

In [6]:
df=pd.DataFrame(A,columns=['Station'])
df['Max']=B
df['Min']=C
df['Rain']=D
df

          Station   Max   Min  Rain
0         Dipayal  34.0  15.8   0.0
1      Dadeldhura  24.8  11.3   0.0
2        Dhangadi  34.5  20.2   0.0
3   Birendranagar  31.5  16.5   0.0
4       Nepalgunj  34.2  21.4   0.0
5           Jumla  23.6  11.5   0.0
6            Dang  33.0  17.0   0.0
7         Pokhara  31.2  18.5   0.0
8      Bhairahawa  36.4  21.6   0.0
9          Simara  35.4  20.0   0.0
10      Kathmandu  30.5  14.4   0.0
11    Okhaldhunga  27.2  16.6   0.0
12      Taplejung  27.0  13.8   0.0
13       Dhankuta  29.6  16.4   0.0
14     Biratnagar  34.0  22.0   0.0
15         Jomsom  19.0   8.5  0.0*
16          Lumle  24.5  14.5  0.0*
17       Jankapur  34.2  23.8  0.0*
18           Jiri  26.0   9.5  0.0*